version: "3.1"
services:
  db:
    container_name: db_mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: stock
    networks:
      - concurrency
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - concurrency

networks:
  concurrency:
